version: '3.1'

services:
  kafka:
    container_name: kafka
    image: spotify/kafka
    hostname: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - crowdnav_network

  crowdnav:
    build: .
    container_name: crowdnav
    hostname: crowdnav
    networks:
      - crowdnav_network
    depends_on:
      - kafka

networks:
  crowdnav_network: