version: '3.1'

services:
  kafka:
    container_name: kafka
    image: spotify/kafka
    hostname: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=172.18.0.2
    networks:
      crowdnav_network:
        ipv4_address: 172.18.0.2

  crowdnav:
    build: .
    container_name: crowdnav
    hostname: crowdnav
    networks:
      - crowdnav_network
    depends_on:
      - kafka

networks:
  crowdnav_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.2/16
